name: Tag and Release
on:
    push:
        branches: ["master", "main"]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    tag_and_release:
        uses: SpalkLtd/github-reusable-workflows/.github/workflows/tagandrelease.yml@main
