name: Tag Cut Version PR's

on:
    push:
        branches: ["master", "main"]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    if_merged:
        # if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - run: |
                  BRANCH_NAME="${{ github.head_ref }}"
                  echo "BRANCH IS: ${BRANCH_NAME}"
                  echo "GOT github.ref: ${{github.ref}}"
                  echo "GOT github.ref_name: ${{github.ref_name}}"
                  echo "GOT github.event.pull_request.base.ref: ${{github.event.pull_request.base.ref}}"
                  echo VERSION NUMBER IS ${BRANCH_NAME##*-}
                  echo "TEST"
                  export LATESTLOG=$(git log -1 --pretty=%B)
                  export SOURCEBRANCH=$(echo $LATESTLOG | awk -F '\\\\n' '{print $1}' |  awk -F '/' '{print $2}' | awk '{print $1}')
